name: "Build & Test"

on: [push, pull_request]

jobs:
  job:
    name: "${{ matrix.os_label }}, ${{ matrix.cc }}, ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [macos-clang]
        include:
          - name: macos-clang
            os: macos-latest
            os_label: MacOS
            cxx: clang++
            cc: clang

        build_type: [Release]

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install dependencies"
      run: brew install coreutils googletest

    - name: "Build code"
      run: make -j8

    - name: "Run unit tests"
      run: |
        set CTEST_OUTPUT_ON_FAILURE=1
        ./build/linux/x86_64/release/ci_test
