name: "Build & Test"

on: [push, pull_request]

jobs:
  job:
    name: "${{ matrix.os_label }}, ${{ matrix.cc }}, ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [macos-clang, macos-gcc]
        include:
          - name: macos-clang
            os: macos-latest
            os_label: MacOS
            cxx: clang++
            cc: clang

          - name: macos-gcc
            os: macos-latest
            os_label: MacOS
            cxx: g++
            cc: gcc

        build_type: [Release, Debug]

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install cmake"
      uses: lukka/get-cmake@latest

    - name: "Install dependencies"
      run: brew install coreutils googletest

    - name: "Configure"
      run: cmake -B build -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DCMAKE_CXX_COMPILER="${{ matrix.cxx }}" -DCMAKE_C_COMPILER="${{ matrix.cc }}"

    - name: "Build code"
      run: cmake --build build --config "${{ matrix.build_type }}"

    - name: "Run unit tests"
      run: |
        cd build
        set CTEST_OUTPUT_ON_FAILURE=1
        ./build/linux/x86_64/release/ci_test
